# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupAlimentos', '0002_promocao_esta_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanche',
            name='valor',
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
