# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startupAlimentos', '0002_ingrediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LancheIngrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupAlimentos.Ingrediente')),
                ('lanche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startupAlimentos.Lanche')),
            ],
        ),
        migrations.AddField(
            model_name='lanche',
            name='ingredientes',
            field=models.ManyToManyField(through='startupAlimentos.LancheIngrediente', to='startupAlimentos.Ingrediente'),
        ),
    ]
