# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startupAlimentos', '0003_auto_20170328_2337'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocao',
        ),
    ]
